integralfamilies:
  - name: "B2"
    loop_momenta: [q1, q2]
    top_level_sectors: [b110111001]
    propagators:
      - ["q1",                mm^2]
      - ["q2",                mm^2]
      - ["p3 + q1",           0   ]
      - ["p1 + p2 + q2",      mm^2]
      - ["p3 + q1 + q2",      mm^2]
      - ["-p1 - p2 + p3 + q1",0   ]
      - ["p1 + q2",           0   ]
      - ["p1 + q1",           0   ]
      - ["p3 + q2",           0   ]

