(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[B0, {MH}, 1, 0], userIntegral[B0, {mz}, 1, 0], 
 userIntegral[B0, {mw}, 1, 0], userIntegral[A0, {0}, 0, 1], 
 userIntegral[A0, {0}, 1, 0], userIntegral[A0, {0}, 1, 1], 
 userIntegral[A0, {0}, -1, 1], userIntegral[A0, {0}, 0, 0], 
 userIntegral[A0, {0}, 1, -1], userIntegral[B0, {ME}, 1, 1], 
 userIntegral[B0, {ME}, 0, 1], userIntegral[B0, {ME}, 1, 0], 
 userIntegral[B0, {ME}, -1, 1], userIntegral[B0, {ME}, 0, 0], 
 userIntegral[B0, {ME}, 1, -1], userIntegral[B0, {mm}, 1, 1], 
 userIntegral[B0, {mm}, 0, 1], userIntegral[B0, {mm}, 1, 0], 
 userIntegral[B0, {mm}, -1, 1], userIntegral[B0, {mm}, 0, 0], 
 userIntegral[B0, {mm}, 1, -1], userIntegral[B0, {ML}, 1, 1], 
 userIntegral[B0, {ML}, 0, 1], userIntegral[B0, {ML}, 1, 0], 
 userIntegral[B0, {ML}, -1, 1], userIntegral[B0, {ML}, 0, 0], 
 userIntegral[B0, {ML}, 1, -1], userIntegral[B0, {mu}, 1, 1], 
 userIntegral[B0, {mu}, 0, 1], userIntegral[B0, {mu}, 1, 0], 
 userIntegral[B0, {mu}, -1, 1], userIntegral[B0, {mu}, 0, 0], 
 userIntegral[B0, {mu}, 1, -1], userIntegral[B0, {MC}, 1, 1], 
 userIntegral[B0, {MC}, 0, 1], userIntegral[B0, {MC}, 1, 0], 
 userIntegral[B0, {MC}, -1, 1], userIntegral[B0, {MC}, 0, 0], 
 userIntegral[B0, {MC}, 1, -1], userIntegral[B0, {MT}, 1, 1], 
 userIntegral[B0, {MT}, 0, 1], userIntegral[B0, {MT}, 1, 0], 
 userIntegral[B0, {MT}, -1, 1], userIntegral[B0, {MT}, 0, 0], 
 userIntegral[B0, {MT}, 1, -1], userIntegral[B0, {md}, 1, 1], 
 userIntegral[B0, {md}, 0, 1], userIntegral[B0, {md}, 1, 0], 
 userIntegral[B0, {md}, -1, 1], userIntegral[B0, {md}, 0, 0], 
 userIntegral[B0, {md}, 1, -1], userIntegral[B0, {MS}, 1, 1], 
 userIntegral[B0, {MS}, 0, 1], userIntegral[B0, {MS}, 1, 0], 
 userIntegral[B0, {MS}, -1, 1], userIntegral[B0, {MS}, 0, 0], 
 userIntegral[B0, {MS}, 1, -1], userIntegral[B0, {MB}, 1, 1], 
 userIntegral[B0, {MB}, 0, 1], userIntegral[B0, {MB}, 1, 0], 
 userIntegral[B0, {MB}, -1, 1], userIntegral[B0, {MB}, 0, 0], 
 userIntegral[B0, {MB}, 1, -1], userIntegral[C0, {MH, mz}, 1, 1], 
 userIntegral[C0, {MH, mz}, 0, 1], userIntegral[C0, {MH, mz}, 1, 0], 
 userIntegral[C0, {MH, mz}, -1, 1], userIntegral[C0, {MH, mz}, 0, 0], 
 userIntegral[C0, {MH, mz}, 1, -1], userIntegral[B0, {mw}, 1, 1], 
 userIntegral[B0, {mw}, 0, 1], userIntegral[B0, {mw}, -1, 1], 
 userIntegral[B0, {mw}, 0, 0], userIntegral[B0, {mw}, 1, -1]}
