(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[B0, {MH}, 1, 0], userIntegral[B0, {MZ}, 1, 0], 
 userIntegral[B0, {MW}, 1, 0], userIntegral[A0, {0}, 0, 1], 
 userIntegral[A0, {0}, 1, 0], userIntegral[A0, {0}, 1, 1], 
 userIntegral[A0, {0}, -1, 1], userIntegral[A0, {0}, 0, 0], 
 userIntegral[A0, {0}, 1, -1], userIntegral[B0, {ME}, 1, 1], 
 userIntegral[B0, {ME}, 0, 1], userIntegral[B0, {ME}, 1, 0], 
 userIntegral[B0, {ME}, -1, 1], userIntegral[B0, {ME}, 0, 0], 
 userIntegral[B0, {ME}, 1, -1], userIntegral[B0, {MM}, 1, 1], 
 userIntegral[B0, {MM}, 0, 1], userIntegral[B0, {MM}, 1, 0], 
 userIntegral[B0, {MM}, -1, 1], userIntegral[B0, {MM}, 0, 0], 
 userIntegral[B0, {MM}, 1, -1], userIntegral[B0, {ML}, 1, 1], 
 userIntegral[B0, {ML}, 0, 1], userIntegral[B0, {ML}, 1, 0], 
 userIntegral[B0, {ML}, -1, 1], userIntegral[B0, {ML}, 0, 0], 
 userIntegral[B0, {ML}, 1, -1], userIntegral[B0, {MU}, 1, 1], 
 userIntegral[B0, {MU}, 0, 1], userIntegral[B0, {MU}, 1, 0], 
 userIntegral[B0, {MU}, -1, 1], userIntegral[B0, {MU}, 0, 0], 
 userIntegral[B0, {MU}, 1, -1], userIntegral[B0, {MC}, 1, 1], 
 userIntegral[B0, {MC}, 0, 1], userIntegral[B0, {MC}, 1, 0], 
 userIntegral[B0, {MC}, -1, 1], userIntegral[B0, {MC}, 0, 0], 
 userIntegral[B0, {MC}, 1, -1], userIntegral[B0, {MT}, 1, 1], 
 userIntegral[B0, {MT}, 0, 1], userIntegral[B0, {MT}, 1, 0], 
 userIntegral[B0, {MT}, -1, 1], userIntegral[B0, {MT}, 0, 0], 
 userIntegral[B0, {MT}, 1, -1], userIntegral[B0, {MD}, 1, 1], 
 userIntegral[B0, {MD}, 0, 1], userIntegral[B0, {MD}, 1, 0], 
 userIntegral[B0, {MD}, -1, 1], userIntegral[B0, {MD}, 0, 0], 
 userIntegral[B0, {MD}, 1, -1], userIntegral[B0, {MS}, 1, 1], 
 userIntegral[B0, {MS}, 0, 1], userIntegral[B0, {MS}, 1, 0], 
 userIntegral[B0, {MS}, -1, 1], userIntegral[B0, {MS}, 0, 0], 
 userIntegral[B0, {MS}, 1, -1], userIntegral[B0, {MB}, 1, 1], 
 userIntegral[B0, {MB}, 0, 1], userIntegral[B0, {MB}, 1, 0], 
 userIntegral[B0, {MB}, -1, 1], userIntegral[B0, {MB}, 0, 0], 
 userIntegral[B0, {MB}, 1, -1], userIntegral[C0, {MH, MZ}, 1, 1], 
 userIntegral[C0, {MH, MZ}, 0, 1], userIntegral[C0, {MH, MZ}, 1, 0], 
 userIntegral[C0, {MH, MZ}, -1, 1], userIntegral[C0, {MH, MZ}, 0, 0], 
 userIntegral[C0, {MH, MZ}, 1, -1], userIntegral[B0, {MW}, 1, 1], 
 userIntegral[B0, {MW}, 0, 1], userIntegral[B0, {MW}, -1, 1], 
 userIntegral[B0, {MW}, 0, 0], userIntegral[B0, {MW}, 1, -1]}
