integralfamilies:
  - name: "A1"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A1>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]

  - name: "A2"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A2>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]

