 integralfamilies:
##BASIS
  - name: "TopoCM"
    loop_momenta: [q1]
    top_level_sectors: [15]
    propagators:
      - [ "q1", 0] #1
      - [ "-p1+q1", m1^2] #2
      - [ "p2+q1", 0] #3
      - [ "p3-p1+q1", 0] #4
  - name: "TopoCMp"
    loop_momenta: [q1]
    top_level_sectors: [15]
    propagators:
      - [ "q1", 0] #1
      - [ "-p1+q1", 0] #2
      - [ "p2+q1", m1^2] #3
      - [ "-p3+p2+q1", 0] #4
  - name: "TopoC2M"
    loop_momenta: [q1]
    top_level_sectors: [15]
    propagators:
      - [ "q1", 0] #1
      - [ "-p1+q1", m1^2] #2
      - [ "p2+q1", m2^2] #3
      - [ "p3-p1+q1", 0] #4
  - name: "TopoC2Mp"
    loop_momenta: [q1]
    top_level_sectors: [15]
    propagators:
      - [ "q1", 0] #1
      - [ "-p1+q1", m1^2] #2
      - [ "p2+q1", m2^2] #3
      - [ "-p3+p2+q1", 0] #4         
