(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[A1, {0}, -1, 2], userIntegral[A1, {0}, 0, 1], 
 userIntegral[A1, {0}, 0, 2], userIntegral[A1, {0}, 1, 0], 
 userIntegral[A1, {0}, 1, 1], userIntegral[A1, {0}, 1, 2], 
 userIntegral[A2, {mz*Sqrt[GaugeXi[Q]]}, 0, 0], 
 userIntegral[A2, {mz*Sqrt[GaugeXi[Q]]}, 0, 1], 
 userIntegral[A2, {mz*Sqrt[GaugeXi[Q]]}, 1, -1], 
 userIntegral[A2, {mz*Sqrt[GaugeXi[Q]]}, 1, 0], 
 userIntegral[A2, {mz*Sqrt[GaugeXi[Q]]}, 1, 1], userIntegral[A2, {mz}, 0, 0], 
 userIntegral[A2, {mz}, 0, 1], userIntegral[A2, {mz}, 1, -1], 
 userIntegral[A2, {mz}, 1, 0], userIntegral[A2, {mz}, 1, 1], 
 userIntegral[A2, {mw*Sqrt[GaugeXi[Q]]}, 0, 0], 
 userIntegral[A2, {mw*Sqrt[GaugeXi[Q]]}, 0, 1], 
 userIntegral[A2, {mw*Sqrt[GaugeXi[Q]]}, 1, -1], 
 userIntegral[A2, {mw*Sqrt[GaugeXi[Q]]}, 1, 0], 
 userIntegral[A2, {mw*Sqrt[GaugeXi[Q]]}, 1, 1], userIntegral[A2, {mw}, 0, 0], 
 userIntegral[A2, {mw}, 0, 1], userIntegral[A2, {mw}, 1, -1], 
 userIntegral[A2, {mw}, 1, 0], userIntegral[A2, {mw}, 1, 1]}
