LIBS += $(LIB)

OBJS := \
  $(DIR)abbr1s.o \
  $(DIR)abbr1a.o \
  $(DIR)abbr1h1.o \
  $(DIR)abbr1h2.o \
  $(DIR)abbr1h3.o \
  $(DIR)box_Gen5.o \
  $(DIR)box.o \
  $(DIR)SquaredME.o

$(LIB): $(LIB)($(OBJS))

$(LIB)($(OBJS)): F-squaredme.d $(DIR)vars.h

