#if 0
* specs.h
* process specifications
* generated by FormCalc 9.10 (30 Aug 2022) on 19-Jan-2023 15:01
#endif

#undef FCVERSION
#define FCVERSION "FormCalc 9.10 (30 Aug 2022)"

#undef PROCNAME
#define PROCNAME "V1V1V1V1"

#undef SQUAREDME_FUNC
#define SQUAREDME_FUNC SquaredME

#undef KIN
#define KIN "2to2.F"

#undef IDENTICALFACTOR
#define IDENTICALFACTOR 2

#undef DIRACFERMIONS
#define DIRACFERMIONS 0

#undef Compose
#define Compose(f,c,A,B,C,D) c(c(c(f(A,1,1),f(B,2,1)),f(C,3,2)),f(D,4,2))

#undef Crossing
#define Crossing(f,c) Compose(f,c,1,2,3,4)

#undef Generic
#define Generic(f,c) Compose(f,c,PHOTON,PHOTON,PHOTON,PHOTON)

#undef Anti
#define Anti(f,c) Compose(f,c,1,1,1,1)

#undef Mass
#define Mass(f,c) Compose(f,c,0,0,0,0)

