integralfamilies:
  - name: "D66"
    loop_momenta: [q1, q2]
    top_level_sectors: [b1111110]
    propagators:
      - ["q1",                m1^2]
      - ["q2",                m1^2]
      - ["-p1 + q1",          m1^2]
      - ["-p2 + q1",          m2^2]
      - ["-p1 + p2 + q2",     m3^2]
      - ["-p1 + q1 + q2",     m2^2]
      - ["p1 + q2",           0   ]

