 integralfamilies:
##BASIS
  - name: "A1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "q2", 0]
      - [ "q1+q2", m1^2]
      - [ "p1-q1", 0]
      - [ "p1-q2", 0]
      - [ "p1+p2-q1", 0]
      - [ "q2+p3-p1-p2", m1^2]
      - [ "q1-p3", 0]
      - [ "q2+p3", m1^2]
  - name: "B2"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "p3+q1", 0]
      - [ "q1+p3-p1-p2", 0]
      - [ "q2", m1^2]
      - [ "p1+p2+q2", m1^2]
      - [ "p3+q1+q2", m1^2]
      - [ "q2+p1", 0]
      - [ "q1+p1", 0]
      - [ "q2+p3", 0]
  - name: "B3"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", 0]
      - [ "p3+q1", m1^2]
      - [ "q1+p3-p1-p2", m1^2]
      - [ "q2", m1^2]
      - [ "p1+p2+q2", m1^2]
      - [ "p3+q1+q2", 0]
      - [ "q2+p1", 0]
      - [ "q1+p1", 0]
      - [ "q2+p3", 0]
  - name: "D1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "q2", 0]
      - [ "q1+q2-p1-p2", m1^2]
      - [ "q2+p3-p1-p2", m1^2]
      - [ "q1+q2", m1^2]
      - [ "q1-p3", 0]
      - [ "q2+p1", 0]
      - [ "q2+p3", 0]
      - [ "p2-q1", 0]
  - name: "E1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", 0]
      - [ "q2", m1^2]
      - [ "q1+p3", m1^2]
      - [ "q1+p3-p1-p2", m1^2]
      - [ "-p3-q1+q2", 0]
      - [ "q1+q2-p1-p2", 0]
      - [ "q1+q2", 0]
      - [ "p1+q1", 0]
      - [ "q2+p2", 0]
  - name: "F1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", 0]
      - [ "q2", m1^2]
      - [ "q1+p3", m1^2]
      - [ "q1+p3-p1-p2", m1^2]
      - [ "q1+q2+p3-p1-p2", 0]
      - [ "q1+q2", 0]
      - [ "p1+q2", 0]
      - [ "q2+p2", 0]
      - [ "p2+q1", 0]
  - name: "G1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "q2", m1^2]
      - [ "q1+p3", 0]
      - [ "q1+p1+p2", m1^2]
      - [ "p3+q1-q2", m1^2]
      - [ "q2+p1", 0]
      - [ "q1+q2", 0]
      - [ "p1+q1", 0]
      - [ "q2+p2", 0]
  - name: "B1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "p3+q1", 0]
      - [ "q1+p3-p1-p2", 0]
      - [ "q2", m2^2]
      - [ "p1+p2+q2", m2^2]
      - [ "p3+q1+q2", m2^2]
      - [ "q2+p1", 0]
      - [ "q1+p1", 0]
      - [ "q2+p3", 0]
  - name: "C1"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "q1+p1+p2", m1^2]
      - [ "p3+q1", 0]
      - [ "q2", m1^2]
      - [ "q2+p3-p1-p2", 0]
      - [ "p3+q1+q2", m2^2]
      - [ "q2+q1", 0]
      - [ "q1+p1", 0]
      - [ "q2+p1", 0]
  - name: "G2"
    loop_momenta: [q1,q2]
    top_level_sectors: [511]
    propagators:
      - [ "q1", m1^2]
      - [ "q2", m2^2]
      - [ "q1+p3", 0]
      - [ "q1+p1+p2", m1^2]
      - [ "p3+q1-q2", m2^2]
      - [ "q2+p1", 0]
      - [ "q1+q2", 0]
      - [ "p1+q1", 0]
      - [ "q2+p2", 0]