integralfamilies:
  - name: "A1"
    loop_momenta: [q1]
    top_level_sectors: [b1110]
    propagators:
      - ["q1",                0   ]
      - ["p3 + q1",           0   ]
      - ["-p1 - p2 + p3 + q1",0   ]
      - ["p1 + q1",           0   ]

  - name: "A2"
    loop_momenta: [q1]
    top_level_sectors: [b1110]
    propagators:
      - ["q1",                m1^2]
      - ["p3 + q1",           0   ]
      - ["-p1 - p2 + p3 + q1",0   ]
      - ["p1 + q1",           0   ]

  - name: "A3"
    loop_momenta: [q1]
    top_level_sectors: [b1110]
    propagators:
      - ["q1",                0   ]
      - ["p3 + q1",           m1^2]
      - ["-p1 - p2 + p3 + q1",m1^2]
      - ["p1 + q1",           0   ]

