integralfamilies:
  - name: "A1"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A1>
    propagators:
      - ["q1",                0   ]
      - ["p3 + q1",           m1^2]
      - ["-p1 - p2 + p3 + q1",m1^2]
      - ["-p1 + q1",          0   ]

