integralfamilies:
  - name: "A5"
    loop_momenta: [q1]
    top_level_sectors: [b0111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     m1^2]

