jobs:
 - reduce_sectors:
    reduce:
     - {sectors: [511], r: 9, s: 3}
    select_integrals:
     select_mandatory_recursively:
      - {sectors: [511], r: 9, s: 3}
    preferred_masters: my_basis
    run_initiate: true
    run_triangular: true
    run_back_substitution: true
