integralfamilies:
  - name: "A1"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A1>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A2"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A2>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A3"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A3>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A4"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A4>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m2^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "B1"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_B1>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["p2 - p3 + q1",      0   ]

  - name: "B2"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_B2>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           m1^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "B4"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_B4>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m2^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "B3"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_B3>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m1^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "A5"
    loop_momenta: [q1]
    top_level_sectors: <SECTOR_A5>
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     m1^2]

