integralfamilies:
  - name: "G1"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_G1>
    propagators:
      - ["q1",                m1^2]
      - ["q2",                m1^2]
      - ["p3 + q1",           0   ]
      - ["p1 + p2 + q1",      m1^2]
      - ["p3 + q1 - q2",      m1^2]
      - ["p1 + q2",           0   ]
      - ["q1 + q2",           0   ]
      - ["p1 + q1",           0   ]
      - ["p2 + q2",           0   ]

