(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[A0, {ME}, 1, 1], userIntegral[A0, {ME}, 0, 1], 
 userIntegral[A0, {ME}, 1, 0], userIntegral[A0, {MM}, 1, 1], 
 userIntegral[A0, {MM}, 0, 1], userIntegral[A0, {MM}, 1, 0], 
 userIntegral[A0, {ML}, 1, 1], userIntegral[A0, {ML}, 0, 1], 
 userIntegral[A0, {ML}, 1, 0], userIntegral[A0, {MU}, 1, 1], 
 userIntegral[A0, {MU}, 0, 1], userIntegral[A0, {MU}, 1, 0], 
 userIntegral[A0, {MC}, 1, 1], userIntegral[A0, {MC}, 0, 1], 
 userIntegral[A0, {MC}, 1, 0], userIntegral[A0, {MT}, 1, 1], 
 userIntegral[A0, {MT}, 0, 1], userIntegral[A0, {MT}, 1, 0], 
 userIntegral[A0, {MD}, 1, 1], userIntegral[A0, {MD}, 0, 1], 
 userIntegral[A0, {MD}, 1, 0], userIntegral[A0, {MS}, 1, 1], 
 userIntegral[A0, {MS}, 0, 1], userIntegral[A0, {MS}, 1, 0], 
 userIntegral[A0, {MB}, 1, 1], userIntegral[A0, {MB}, 0, 1], 
 userIntegral[A0, {MB}, 1, 0], userIntegral[A0, {MW}, 1, 1], 
 userIntegral[A0, {MW}, 0, 1], userIntegral[A0, {MW}, 1, 0]}
