(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[E0, {me}, 0, 1], userIntegral[E0, {me}, 1, 0], 
 userIntegral[E0, {me}, 1, 1], userIntegral[E0, {mm}, 0, 1], 
 userIntegral[E0, {mm}, 1, 0], userIntegral[E0, {mm}, 1, 1], 
 userIntegral[E0, {ml}, 0, 1], userIntegral[E0, {ml}, 1, 0], 
 userIntegral[E0, {ml}, 1, 1], userIntegral[C0, {mu, md}, 1, 1], 
 userIntegral[C0, {mu, md}, 0, 1], userIntegral[C0, {mu, md}, 1, 0], 
 userIntegral[C0, {mc, ms}, 1, 1], userIntegral[C0, {mc, ms}, 0, 1], 
 userIntegral[C0, {mc, ms}, 1, 0], userIntegral[C0, {mt, mb}, 1, 1], 
 userIntegral[C0, {mt, mb}, 0, 1], userIntegral[C0, {mt, mb}, 1, 0], 
 userIntegral[C0, {mh, mw}, 1, 1], userIntegral[C0, {mh, mw}, 0, 1], 
 userIntegral[C0, {mh, mw}, 1, 0], userIntegral[C0, {mz, mw}, 1, 1], 
 userIntegral[C0, {mz, mw}, 0, 1], userIntegral[C0, {mz, mw}, 1, 0], 
 userIntegral[E0, {mw}, 1, 1], userIntegral[E0, {mw}, 0, 1], 
 userIntegral[E0, {mw}, 1, 0], userIntegral[D0, {mw}, 1, 1], 
 userIntegral[C0, {mw, mz}, 1, 1]}
