integralfamilies:
  - name: "A11"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

