{gZlL[1]->(I3l1 -Ql1*sw^2)/(cw*sw),
gZlR[1]->(-Ql1*sw^2)/(cw*sw),
gZlL[2]->(I3l2 -Ql2*sw^2)/(cw*sw),
gZlR[2]->(-Ql2*sw^2)/(cw*sw),
gZlL[3]->(I3l3 -Ql3*sw^2)/(cw*sw),
gZlR[3]->(-Ql3*sw^2)/(cw*sw),
gZNL[1]->(I3N1)/(cw*sw),
gZNL[2]->(I3N2)/(cw*sw),
gZNL[3]->(I3N3)/(cw*sw),
gZuL[1]->(I3u1 - (Qu1*sw^2))/(cw*sw),
gZuR[1]->(-Qu1*sw^2)/(cw*sw),
gZuL[2]->(I3u2 - (Qu2*sw^2))/(cw*sw),
gZuR[2]->(-Qu2*sw^2)/(cw*sw),
gZuL[3]->(I3u3 - (Qu3*sw^2))/(cw*sw),
gZuR[3]->(-Qu3*sw^2)/(cw*sw),
gZdL[1]->(I3d1 - (Qd1*sw^2))/(cw*sw),
gZdR[1]->(-Qd1*sw^2)/(cw*sw),
gZdL[2]->(I3d2 - (Qd2*sw^2))/(cw*sw),
gZdR[2]->(-Qd2*sw^2)/(cw*sw),
gZdL[3]->(I3d3 - (Qd3*sw^2))/(cw*sw),
gZdR[3]->(-Qd3*sw^2)/(cw*sw),
gAl[1]->-Ql1,
gAl[2]->-Ql2,
gAl[3]->-Ql3,
gAu[1]->-Qu1,
gAu[2]->-Qu2,
gAu[3]->-Qu3,
gAd[1]->-Qd1,
gAd[2]->-Qd2,
gAd[3]->-Qd3,
gWNl->1/(Sqrt[2]*sw),
gWlN->1/(Sqrt[2]*sw),
gWud->1/(Sqrt[2]*sw),
gWdu->1/(Sqrt[2]*sw),
gWWZ->cw/sw,
gWWA->1,
gWWWW->1/(sw^2),
gWWZZ->-(cw^2)/(sw^2),
gWWAZ->(cw)/(sw),
gWWAA->-1,
gHHHH->((-3)/(4*sw^2*mw^2)),
gXXXX->((-3)/(4*sw^2*mw^2)),
gHHXX->(1/(2*sw^2)),
gHHFF->(1/(2*sw^2)),
gXXFF->(1/(2*sw^2)),
gFFFF->(1/(2*sw^2)),
gHXFF->1/(4*cw^2),
gHHH->(-3/(2*mw*sw)),
gHXX->(-1/(2*mw*sw)),
gHFF->(-1/(2*mw*sw)),
gXFF->(mw*sw)/(2*cw^2),
gHHZZ->1/(2*cw^2*sw^2),
gXXZZ->1/(2*cw^2*sw^2),
gHHWW->1/(2*sw^2),
gXXWW->1/(2*sw^2),
gFFWW->1/(2*sw^2),
gFFAA->2,
gFFAZ->(-cw^2 + sw^2)/(cw*sw),
gFFZZ->(-cw^2 + sw^2)^2/(2*cw^2*sw^2),
gHFAW->(-1)/(2*sw),
gHFZW->(-1)/(2*cw),
gXFAW->1/(2*sw),
gXFZW->1/(2*cw),
gHFZW->(-1)/(2*cw),
gHXWW->1/(2*sw^2),
gHXZ->1/(2*cw*sw),
gFFA->1,
gFFZ->(cw^2 - sw^2)/(2*cw*sw),
gHFW->1/(2*sw),
gXFW->1/(2*sw),
gHZZ->mw/(cw^2*sw),
gHWW->mw/sw,
gXWW->mw/sw,
gFAW->(-mw),
gFZW->mw/cw,
gHll->(-1)/(2*sw*mw),
gHuu->(-1)/(2*sw*mw),
gHdd->(-1)/(2*sw*mw),
gXll->1/(2*sw*mw),
gXuu->1/(2*sw*mw),
gXdd->1/(2*sw*mw),
gFll->1/(Sqrt[2]*mw*sw),
gFud->1/(Sqrt[2]*mw*sw),
gFdu->1/(Sqrt[2]*mw*sw),
ggpgpA->1,
ggmgmA->1,
ggpgpZ->cw/sw,
ggmgmZ->cw/sw,
ggzgpW->cw/sw,
ggzgmW->cw/sw,
ggagpW->1,
ggagmW->1,
gHgzgz->(-mw)/(cw^2*sw),
gHgpgp->(-mw)/sw,
gHgmgm->-mw/sw,
gXgpgp->mw/(2*sw),
gXgmgm->mw/(2*sw),
gFgzgp->mw/cw,
gFgzgm->mw/cw,
gFgagm->mw,
gFgagp->mw,
ggpgpAA->1,
ggmgmAA->1,
ggpgpAZ->(-cw)/sw,
ggmgmAZ->(-cw/sw),
ggpgpZZ->cw^2/sw^2,
ggmgmZZ->cw^2/sw^2,
ggagpAW->(-1),
ggagmAW->(-1),
ggagpZW->cw/sw,
ggagmZW->cw/sw,
ggzgpAW->cw/sw,
ggzgmAW->cw/sw,
ggzgpZW->(-cw^2)/sw^2,
ggzgmZW->(-cw^2/sw^2),
ggagaWW->1,
ggagzWW->(-cw)/sw,
ggzgzWW->cw^2/sw^2,
ggpgpWW->1/sw^2,
ggmgmWW->1/sw^2,
ggpgmWW->(-1)/sw^2,
gHHgzgz->(-1)/(2*cw^2*sw^2),
gHHgpgp->(-1)/(2*sw^2),
gHHgmgm->(-1)/(2*sw^2),
gXXgzgz->(-1)/(2*cw^2*sw^2),
gXXgpgp->(-1)/(2*sw^2),
gXXgmgm->(-1)/(2*sw^2),
gFFgaga->(-1),
gFFgzgz->(cw^2 - sw^2)^2/(2*cw^2*sw^2),
gFFgpgp->(-1)/(2*sw^2),
gFFgmgm->(-1)/(2*sw^2),
gFFgagz->(cw^2 - sw^2)/(cw*sw),
gHXgpgp->1/(4*sw^2),
gHXgmgm->1/(4*sw^2),
gHFgagp->1/(2*sw),
gHFgagm->1/(2*sw),
gHFgzgp->1/(2*cw),
gHFgzgm->1/(2*cw),
gXFgagp->1/(2*sw),
gXFgagm->1/(2*sw),
gXFgzgp->1/(2*cw),
gXFgzgm->1/(2*cw)}