(* Created with the Wolfram Language : www.wolfram.com *)
{userIntegral[E0, {ME}, 0, 1], userIntegral[E0, {ME}, 1, 0], 
 userIntegral[E0, {ME}, 1, 1], userIntegral[E0, {mm}, 0, 1], 
 userIntegral[E0, {mm}, 1, 0], userIntegral[E0, {mm}, 1, 1], 
 userIntegral[E0, {ML}, 0, 1], userIntegral[E0, {ML}, 1, 0], 
 userIntegral[E0, {ML}, 1, 1], userIntegral[C0, {mu, md}, 1, 1], 
 userIntegral[C0, {mu, md}, 0, 1], userIntegral[C0, {mu, md}, 1, 0], 
 userIntegral[C0, {MC, MS}, 1, 1], userIntegral[C0, {MC, MS}, 0, 1], 
 userIntegral[C0, {MC, MS}, 1, 0], userIntegral[C0, {MT, MB}, 1, 1], 
 userIntegral[C0, {MT, MB}, 0, 1], userIntegral[C0, {MT, MB}, 1, 0], 
 userIntegral[C0, {MH, mw}, 1, 1], userIntegral[C0, {MH, mw}, 0, 1], 
 userIntegral[C0, {MH, mw}, 1, 0], userIntegral[C0, {mz, mw}, 1, 1], 
 userIntegral[C0, {mz, mw}, 0, 1], userIntegral[C0, {mz, mw}, 1, 0], 
 userIntegral[E0, {mw}, 1, 1], userIntegral[E0, {mw}, 0, 1], 
 userIntegral[E0, {mw}, 1, 0], userIntegral[D0, {mw}, 1, 1], 
 userIntegral[C0, {mw, mz}, 1, 1]}
