 integralfamilies:
##BASIS
  - name: "A0"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - [ "q1", m1^2] #1
      - [ "p3+q1", m2^2] #2
      - [ "p3+q1-p2-p1", m2^2] #3
      - [ "p3+q1-p1", 0] #4
  - name: "B0"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - [ "q1", 0] #1
      - [ "p3+q1", m1^2] #2
      - [ "p3+q1-p2-p1", m1^2] #3
      - [ "p3+q1-p1", 0] #4
  - name: "C0"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - [ "q1", m1^2] #1
      - [ "p3+q1", 0] #2
      - [ "p3+q1-p2-p1", 0] #3
      - [ "p3+q1-p1", 0] #4
  - name: "D0"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - [ "q1", m1^2] #1
      - [ "p3+q1", m2^2] #2
      - [ "p3+q1-p2-p1", m3^2] #3
      - [ "p3+q1-p1", 0] #4