integralfamilies:
  - name: "H2"
    loop_momenta: [q1, q2]
    top_level_sectors: [b111110000]
    propagators:
      - ["q1",                m1^2]
      - ["q2",                0   ]
      - ["p3 + q1",           m2^2]
      - ["p3 + q1 - q2",      0   ]
      - ["p1 + p2 + q1",      m1^2]
      - ["p3 + q2",           0   ]
      - ["p1 + q1",           0   ]
      - ["p1 + q2",           0   ]
      - ["p2 + q2",           0   ]

