integralfamilies:
  - name: "B0"
    loop_momenta: [q1]
    top_level_sectors: [b1110]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     0   ]

