TopologyList[Process -> {F[3, {1, o}], -F[3, {1, o}]} -> 
    {F[2, {2}], -F[2, {2}]}, Model -> {"SMbgf_Anglerfish_NoUDm"}, 
  GenericModel -> {"Lorentzbgf"}, InsertionLevel -> {Particles}, 
  ExcludeParticles -> {}, ExcludeFieldPoints -> {}, LastSelections -> {}][
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][5], Field[1]], 
   Propagator[Incoming][Vertex[1][2], Vertex[3][5], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][6], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][7], Field[4]], 
   Propagator[Internal][Vertex[3][5], Vertex[3][8], Field[5]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][7], Field[6]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][7], Vertex[3][8], Field[8]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> S, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> S[1], Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> S[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> S[1], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> S[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> S, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> -F[2, {2}], Field[7] -> S[1], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -F[2, {2}], 
      Field[7] -> S[2], Field[8] -> S[2]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> -F[1, {2}], Field[7] -> -S[3], Field[8] -> S[3]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> -F[2, {2}], 
      Field[7] -> S[1], Field[8] -> S[2]], FeynmanGraph[1, Particles == 5][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> -F[2, {2}], Field[7] -> S[2], Field[8] -> S[1]]], 
   FeynmanGraph[1, Generic == 3][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> V, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> V[1], Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> V[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> V[1], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> V[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]]], 
   FeynmanGraph[1, Generic == 4][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> S, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> -F[2, {2}], Field[7] -> S[2], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -F[1, {2}], 
      Field[7] -> -S[3], Field[8] -> V[3]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> -F[2, {2}], Field[7] -> S[1], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -S[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 5][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> V, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> -F[2, {2}], Field[7] -> V[2], Field[8] -> S[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -F[1, {2}], 
      Field[7] -> -V[3], Field[8] -> S[3]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> -F[2, {2}], Field[7] -> V[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -V[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 6][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> V, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> -F[2, {2}], Field[7] -> V[2], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -F[1, {2}], 
      Field[7] -> -V[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 7][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> S, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> S[1], Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> S[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> S[1], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> S[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -S[3], 
      Field[7] -> -F[1, {2}], Field[8] -> F[1, {2}]]], 
   FeynmanGraph[1, Generic == 8][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> S, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> -F[1, {2}], Field[7] -> -S[3], Field[8] -> S[3]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -F[2, {2}], 
      Field[7] -> S[1], Field[8] -> S[2]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> -F[2, {2}], Field[7] -> S[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -S[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 9][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> V, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> V[1], Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> V[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> V[1], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> V[2], 
      Field[7] -> -F[2, {2}], Field[8] -> F[2, {2}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -V[3], 
      Field[7] -> -F[1, {2}], Field[8] -> F[1, {2}]]], 
   FeynmanGraph[1, Generic == 10][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> S, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> -F[2, {2}], Field[7] -> S[1], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -S[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 11][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> V, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> -F[2, {2}], Field[7] -> V[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -V[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 12][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> V, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> -F[1, {2}], Field[7] -> -V[3], Field[8] -> V[3]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -F[1, {2}], 
      Field[7] -> -V[3], Field[8] -> V[3]]]], 
 Topology[1][Propagator[Incoming][Vertex[1][1], Vertex[3][5], Field[1]], 
   Propagator[Incoming][Vertex[1][2], Vertex[3][6], Field[2]], 
   Propagator[Outgoing][Vertex[1][3], Vertex[3][7], Field[3]], 
   Propagator[Outgoing][Vertex[1][4], Vertex[3][7], Field[4]], 
   Propagator[Internal][Vertex[3][7], Vertex[3][8], Field[5]], 
   Propagator[Loop[1]][Vertex[3][5], Vertex[3][6], Field[6]], 
   Propagator[Loop[1]][Vertex[3][5], Vertex[3][8], Field[7]], 
   Propagator[Loop[1]][Vertex[3][6], Vertex[3][8], Field[8]]] -> 
  Insertions[Generic][FeynmanGraph[1, Generic == 1][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> S, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> S[1], Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> S[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -S[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> S[1], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> S[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> -S[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]]], 
   FeynmanGraph[1, Generic == 2][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> S, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[1], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> F[3, {1, o}], 
      Field[7] -> S[2], Field[8] -> S[2]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> F[4, {1, o}], Field[7] -> -S[3], Field[8] -> S[3]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> F[3, {1, o}], 
      Field[7] -> S[1], Field[8] -> S[2]], FeynmanGraph[1, Particles == 5][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[2], Field[8] -> S[1]]], 
   FeynmanGraph[1, Generic == 3][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> V, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> V[1], Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> V[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> -V[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> V[1], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> V[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> -V[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]]], 
   FeynmanGraph[1, Generic == 4][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> S, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[2], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> F[4, {1, o}], 
      Field[7] -> -S[3], Field[8] -> V[3]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[1], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -S[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 5][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> V, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> F[3, {1, o}], Field[7] -> V[2], Field[8] -> S[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> F[4, {1, o}], 
      Field[7] -> -V[3], Field[8] -> S[3]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> V[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -V[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 6][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> S, Field[6] -> F, Field[7] -> V, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> S[10], 
      Field[6] -> F[3, {1, o}], Field[7] -> V[2], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> S[10], Field[6] -> F[4, {1, o}], 
      Field[7] -> -V[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 7][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> S, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> S[1], Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> S[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> -S[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> S[1], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> S[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -S[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]]], 
   FeynmanGraph[1, Generic == 8][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> S, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> F[4, {1, o}], Field[7] -> -S[3], Field[8] -> S[3]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> F[3, {1, o}], 
      Field[7] -> S[1], Field[8] -> S[2]], FeynmanGraph[1, Particles == 3][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -S[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 9][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> V, Field[7] -> F, 
     Field[8] -> F] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> V[1], Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> V[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 3][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[10], Field[6] -> -V[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]], 
     FeynmanGraph[1, Particles == 4][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> V[1], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 5][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> V[2], 
      Field[7] -> F[3, {1, o}], Field[8] -> -F[3, {1, o}]], 
     FeynmanGraph[1, Particles == 6][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> -V[3], 
      Field[7] -> F[4, {1, o}], Field[8] -> -F[4, {1, o}]]], 
   FeynmanGraph[1, Generic == 10][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> S, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> S[1], Field[8] -> V[2]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -S[3], Field[8] -> V[3]]], 
   FeynmanGraph[1, Generic == 11][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> V, 
     Field[8] -> S] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[20], 
      Field[6] -> F[3, {1, o}], Field[7] -> V[2], Field[8] -> S[1]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -V[3], Field[8] -> S[3]]], 
   FeynmanGraph[1, Generic == 12][Field[1] -> F[3, {1, o}], 
     Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
     Field[4] -> F[2, {2}], Field[5] -> V, Field[6] -> F, Field[7] -> V, 
     Field[8] -> V] -> Insertions[Particles][FeynmanGraph[1, Particles == 1][
      Field[1] -> F[3, {1, o}], Field[2] -> -F[3, {1, o}], 
      Field[3] -> -F[2, {2}], Field[4] -> F[2, {2}], Field[5] -> V[10], 
      Field[6] -> F[4, {1, o}], Field[7] -> -V[3], Field[8] -> V[3]], 
     FeynmanGraph[1, Particles == 2][Field[1] -> F[3, {1, o}], 
      Field[2] -> -F[3, {1, o}], Field[3] -> -F[2, {2}], 
      Field[4] -> F[2, {2}], Field[5] -> V[20], Field[6] -> F[4, {1, o}], 
      Field[7] -> -V[3], Field[8] -> V[3]]]]]
