integralfamilies:
  - name: "A1"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_A1>
    propagators:
      - ["q1",                m1^2]
      - ["q2",                0   ]
      - ["q1 + q2",           m1^2]
      - ["p3 + q2",           m1^2]
      - ["-p3 + q1",          0   ]
      - ["-p1 - p2 + p3 + q2",m1^2]
      - ["p1 - q1",           0   ]
      - ["p1 - q2",           0   ]
      - ["p1 + p2 - q1",      0   ]

  - name: "B1"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_B1>
    propagators:
      - ["q1",                0   ]
      - ["q2",                m1^2]
      - ["p3 + q1",           m1^2]
      - ["p1 + p2 + q2",      m1^2]
      - ["p3 + q1 + q2",      0   ]
      - ["-p1 - p2 + p3 + q1",m1^2]
      - ["p1 + q2",           0   ]
      - ["p1 + q1",           0   ]
      - ["p3 + q2",           0   ]

  - name: "B2"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_B2>
    propagators:
      - ["q1",                m1^2]
      - ["q2",                m1^2]
      - ["p3 + q1",           0   ]
      - ["p1 + p2 + q2",      m1^2]
      - ["p3 + q1 + q2",      m1^2]
      - ["-p1 - p2 + p3 + q1",0   ]
      - ["p1 + q2",           0   ]
      - ["p1 + q1",           0   ]
      - ["p3 + q2",           0   ]

  - name: "C1"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_C1>
    propagators:
      - ["q1",                m1^2]
      - ["q2",                0   ]
      - ["q1 + q2",           m1^2]
      - ["-p3 + q1",          0   ]
      - ["-p1 - p2 + p3 + q2",m1^2]
      - ["p1 + p2 - q1 - q2", m1^2]
      - ["p3 + q2",           0   ]
      - ["p1 - q1",           0   ]
      - ["p1 - q2",           0   ]

  - name: "A2"
    loop_momenta: [q1, q2]
    top_level_sectors: <SECTOR_A2>
    propagators:
      - ["q1",                m1^2]
      - ["q2",                0   ]
      - ["q1 + q2",           m2^2]
      - ["p3 + q2",           m2^2]
      - ["-p3 + q1",          0   ]
      - ["-p1 - p2 + p3 + q2",0   ]
      - ["p1 - q1",           0   ]
      - ["p1 - q2",           0   ]
      - ["p1 + p2 - q1",      m1^2]

