integralfamilies:
  - name: "B5"
    loop_momenta: [q1]
    top_level_sectors: [b0111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m2^2]
      - ["p2 - p3 + q1",      0   ]

