integralfamilies:
  - name: "A01p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     0   ]

  - name: "B01p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["p2 - p3 + q1",      0   ]

  - name: "A11p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A12p1"
    loop_momenta: [q1]
    top_level_sectors: [b0111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           0   ]
      - ["-p1 + p3 + q1",     m1^2]

  - name: "B11p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          0   ]
      - ["p2 + q1",           m1^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "A21p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A22p1"
    loop_momenta: [q1]
    top_level_sectors: [b0111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m2^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "A22p2"
    loop_momenta: [q1]
    top_level_sectors: [b0111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m2^2]
      - ["p2 + q1",           m1^2]
      - ["-p1 + p3 + q1",     0   ]

  - name: "B21p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m1^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "B22p1"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m1^2]
      - ["p2 + q1",           m2^2]
      - ["p2 - p3 + q1",      0   ]

  - name: "B22p2"
    loop_momenta: [q1]
    top_level_sectors: [b1111]
    propagators:
      - ["q1",                0   ]
      - ["-p1 + q1",          m2^2]
      - ["p2 + q1",           m1^2]
      - ["p2 - p3 + q1",      0   ]

